export const HOME_FETCH   = 'HOME_FETCH'
export const HOME_FAILURE = 'HOME_FAILURE'
export const HOME_RECV    = 'HOME_RECV'

export const SUBJECT_FETCH = 'SUBJECT_FETCH'
export const SUBJECT_FAILURE = 'SUBJECT_FAILURE'
export const SUBJECT_RECV = 'SUBJECT_RECV'

export const UNIT_FETCH = 'UNIT_FETCH'
export const UNIT_FAILURE = 'UNIT_FAILURE'
export const UNIT_RECV = 'UNIT_RECV'

export const EXERCISE_FETCH = 'EXERCISE_FETCH'
export const EXERCISE_FAILURE = 'EXERCISE_FAILURE'
export const EXERCISE_RECV = 'EXERCISE_RECV'

export const COURSES_FETCH = 'COURSES_FETCH'
export const COURSES_FAILURE = 'COURSES_FAILURE'
export const COURSES_RECV = 'COURSES_RECV'

export const COURSE_FETCH = 'COURSE_FETCH'
export const COURSE_FAILURE = 'COURSE_FAILURE'
export const COURSE_RECV = 'COURSE_RECV'

export const AUTH_TOKEN_FETCH = 'LOGIN_TOKEN_FETCH'
export const AUTH_SUCCESS = 'LOGIN_SUCCESS'
export const AUTH_FAILURE = 'LOGIN_FAILURE'
export const AUTH_IDLE = 'LOGIN_IDLE'